---
datacenter:
  children:
    switches:
      hosts:
        x.x.x.x
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: tbh