---
datacenter:
  children:
    switches:
      hosts:
        192.168.45.200
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: ECh0T@ngo9!!AUTH$